[package]
name = "date_clock"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = "z"
lto = true

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock"]
